language: node_js
node_js:
  - "0.12"

services:
  - mongodb

before_script:
  - npm install bower -g
  - cd public && bower install && cd ..
  - npm install protractor -g
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - nohup bash -c "node_modules/protractor/bin/webdriver-manager update --standalone --firefox"
  - nohup bash -c "nodemodules/protractor/bin/webdriver-manager start 2>&1 &"
  - sleep 5 # give xvfb some time to start



