language: node_js
node_js:
- '0.12'
services:
- mongodb
cache:
  directories:
  - node_modules
  - public/bower_components
before_script:
- npm install bower -g
- cd public && bower install && cd ..
- npm install protractor -g
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
script:
- istanbul cover ./node_modules/mocha/bin/_mocha test/server/**/*.js  --dir ./coverage/server/
  --report lcovonly -- -R spec
- karma start --browsers Firefox --single-run
- "./node_modules/.bin/lcov-result-merger 'coverage/**/*lcov.info' | ./node_modules/coveralls/bin/coveralls.js"
after_script:
- rm -rf ./coverage
deploy:
  provider: heroku
  api_key:
    secure: CiB1Mkhi3xnTxTcPVwKvbEDbFzcp1k4MtJzo564GHfGH8NmiGYSFyXmV2NedcQFqhF5tXADnmhGaJPnUihBwZNMIxvg1h3GVcRni7fqPEHRAdly/ZYcllR2IHeki++7fOOcT6FOfqeX5edlIeJ1wYA5UsJBZKBG0v37jk+Do16gEj05gTsYXkRKCRK0n6wUwBd5WEPtV0CHIiKVRudei7N374f9w91y8eGv8svn80aAVP2af6i1a27se4HDUvy1Bo8aRYqL8E6RHGJ5Ajzv78AJxELqDLiIUtdGZFRcmddrLIqnUyCBQhymN98xN5jWH9Z6kZiuxkdWfw7pv3xmQChTKNfdgWSDEFYG0EflIpnLdDnXqLcfuopFiXjbJbSdvULzQUUC0H33QbtSuDv2AJ7ZoDAPqzcAgMfb/InavD7cqhcgFK7jxIFUs9szBeMusm7Sl5pH+BnRNvjhPEKxNdTwExrNAE7zvYqNRXWRhicH9ajlcIEmXFQdyD8Ur7PJZeA37LrL34l9tk/4ptjqeuo10KjQSyh7vPXGjQ4XMOl9VZpBgVqaLSjip0XS+EUv+k7Vh9kvmAvb3ItRA+Tk/o2/1VZtUMAbunklztJ2zgce0j5hrBEVFarBwQ0LC0lPah0MvpU8lbp5Mmjx7V1xd2xXUpiZoobMgla16eIdWXco=
  app: awesome-social-network
  on:
    repo: vmishevski/AwesomeSocialNetwork
