language: node_js
node_js:
  - "0.12"

services:
  - mongodb

before_script:
  - npm install bower -g
  - cd public && bower install && cd ..
  - npm install protractor -g
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start

test:
  - istanbul cover ./node_modules/mocha/bin/_mocha test/server/**/*.js  --dir ./coverage/server/ --report lcovonly -- -R spec
  - karma start --browsers Firefox --single-run
  - ./node_modules/.bin/lcov-result-merger 'coverage/**/*lcov.info' | ./node_modules/coveralls/bin/coveralls.js

after_test:
  - rm -rf ./coverage