language: node_js
node_js:
- '0.12'
services:
- mongodb
- redis-server
cache:
  directories:
  - node_modules
  - public/bower_components
before_script:
- npm install bower -g
- cd public && bower install && cd ..
- npm install protractor -g
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
script:
- istanbul cover ./node_modules/mocha/bin/_mocha test/server/**/*.js  --dir ./coverage/server/
  --report lcovonly -- -R spec
- karma start --browsers Firefox --single-run
- "./node_modules/.bin/lcov-result-merger 'coverage/**/*lcov.info' | ./node_modules/coveralls/bin/coveralls.js"
- gulp protractor
after_script:
- rm -rf ./coverage
deploy:
  provider: heroku
  api_key: 56e9893f-6a0b-4ab7-8d95-9e52f6309c17
  app: awesome-social-network
  on:
    repo: vmishevski/AwesomeSocialNetwork
env:
- REDIS_URL=localhost NODE_ENV=test DEBUG=app* CLOUDINARY_URL=cloudinary://521814478663666:iphE3U_3sQkuV9ia4egrD8oX6lA@hmfef6ytn